/**
 * Embed /samples into a TypeScript module.
 *
 * The sample documents have to be readable from a serverless function, and
 * embedding them is more dependable than relying on file tracing to pull a
 * directory the code only touches by a computed path.
 *
 *   pnpm samples
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dirname, '..')
const samplesDir = join(root, 'samples')
const out = join(root, 'lib', 'samples.generated.ts')

const ORDER = ['awards.csv', 'program-contract.md', 'amendment-01.md']

type Sample = {
  id: string
  program: string
  name: string
  contentType: string
  body: string
}

const samples: Sample[] = []

for (const dir of readdirSync(samplesDir, { withFileTypes: true })) {
  if (!dir.isDirectory()) continue
  const files = readdirSync(join(samplesDir, dir.name)).sort(
    (a, b) => ORDER.indexOf(a) - ORDER.indexOf(b),
  )
  for (const file of files) {
    samples.push({
      id: `${dir.name}/${file}`,
      program: dir.name,
      name: file,
      contentType: file.endsWith('.csv') ? 'text/csv' : 'text/markdown',
      body: readFileSync(join(samplesDir, dir.name, file), 'utf8'),
    })
  }
}

const header = `// Generated by scripts/build-samples.mts. Do not edit by hand.
// Run \`pnpm samples\` after changing anything in /samples.

export type Sample = {
  id: string
  program: string
  name: string
  contentType: string
  body: string
}

export const SAMPLES: Sample[] = `

writeFileSync(out, header + JSON.stringify(samples, null, 2) + '\n')
console.log(`Wrote ${samples.length} samples to lib/samples.generated.ts`)
